// src/ui/AdminLogin.tsx
// AdminLogin.tsx
import React, { useState } from "react";
import { supabase } from "../services/supabaseClient";
import { useNavigate } from "react-router-dom";

export default function AdminLogin() {
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [errorMsg, setErrorMsg] = useState<string>("");
  const navigate = useNavigate();

  async function handleLogin(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setErrorMsg("");

    const { data, error } = await supabase.auth.signInWithPassword({ email, password });
    if (error) {
      setErrorMsg(error.message);
      return;
    }

    // On attend explicitement que la session soit bien propagée
    let attempts = 0;
    const maxAttempts = 10;
    const delay = 100; // ms

    while (attempts < maxAttempts) {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        navigate("/admin-panel");
        return;
      }
      await new Promise((res) => setTimeout(res, delay));
      attempts++;
    }

    // Si toujours pas de user, afficher un msg
    setErrorMsg("Session non initialisée, veuillez réessayer.");
  }

  return (
    <div className="page">
      <div className="card">
        <h2 className="title">Connexion administrateur</h2>
        <p className="subtitle">Espace réservé aux organisateurs.</p>

        <form onSubmit={handleLogin}>
          <label className="label" htmlFor="email">Email</label>
          <input
            id="email"
            type="email"
            placeholder="nom@exemple.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            className="input"
          />

          <label className="label mt-12" htmlFor="password">Mot de passe</label>
          <input
            id="password"
            type="password"
            placeholder="••••••••"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            className="input"
          />

          <button type="submit" className="btn btn-primary w-100 mt-16">Se connecter</button>
          {errorMsg && <div className="alert alert-error mt-12">{errorMsg}</div>}
        </form>
      </div>
    </div>
  );
}

// src/app/pages/admin-login/admin-login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { NgSupabaseService } from '../../services/supabase.service';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';

@Component({
  standalone: true,
  selector: 'app-admin-login',
  imports: [FormsModule, MatCardModule, MatFormFieldModule, MatInputModule, MatButtonModule],
  templateUrl: './admin-login.component.html',
  styleUrls: ['./admin-login.component.css']
})
export class AdminLoginComponent {
  email = '';
  password = '';
  error = '';

  constructor(private api: NgSupabaseService, private router: Router) {}

  async submit() {
    this.error = '';
    try {
      const { data, error } = await this.api.supabase.auth.signInWithPassword({ email: this.email, password: this.password });
      if (error) throw error;
      // Attendre que la session soit active
      for (let i = 0; i < 10; i++) {
        const { data: { user } } = await this.api.supabase.auth.getUser();
        if (user) {
          await this.router.navigateByUrl('/admin');
          return;
        }
        await new Promise(r => setTimeout(r, 100));
      }
      this.error = 'Session non initialisée, veuillez réessayer.';
    } catch (e: any) {
      this.error = e?.message || 'Erreur de connexion';
    }
  }
}

<div class="page-wrapper">
  <mat-card>
    <mat-card-title>Connexion administrateur</mat-card-title>
    <mat-card-content>
      <form (ngSubmit)="submit()" #f="ngForm" class="grid">
        <mat-form-field appearance="outline">
          <mat-label>Email</mat-label>
          <input matInput id="email" name="email" type="email" [(ngModel)]="email" required />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Mot de passe</mat-label>
          <input matInput id="password" name="password" type="password" [(ngModel)]="password" required />
        </mat-form-field>
        <button mat-raised-button color="primary" type="submit" class="full">Se connecter</button>
        <div *ngIf="error" class="error">{{ error }}</div>
      </form>
    </mat-card-content>
  </mat-card>
</div>
